# Generated by Django 5.2.8 on 2025-11-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='TODO_todo',
        ),
    ]
